{% set name = "conda-package-handling" %}
{% set version = "1.1.0" %}
{% set sha256 = "9eb2a637518e29c55df5ffb89a71ab7dc7049e128ebba7c73befd4dc122f6fc6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/conda/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  # ideally this would work, but this is a conda dep, so we need to be careful.
  # noarch: python
  entry_points:
    - cph = conda_package_handling.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - libarchive >=3.3.3
    - python
    - python-libarchive-c
    - six
    - tqdm

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests

about:
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  summary: Create and extract conda packages of various formats

extra:
  recipe-maintainers:
    - msarahan
