{% set name = "conda-package-handling" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-handling/archive/{{ version }}.tar.gz
  sha256: e26e42b5dc1280237491c025a7e6f23634126463abeace67655c725020d705fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cph = conda_package_handling.cli:main
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.8
    - pip
    - wheel
  run:
    - python >=3.8
    - python
    - conda-package-streaming >=0.9.0
    - zstandard >=0.15

test:
  source_files:
    - tests
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  imports:
    - conda_package_handling
    - conda_package_handling.api
  commands:
    - pytest -v --cov=conda_package_handling --color=yes tests/

about:
  home: https://github.com/conda/conda-package-handling
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Create and extract conda packages of various formats

extra:
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
    - msarahan
